config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #route for new query
  get '/new', to: 'main#new', as: :new
  #creating new query
  post '/new/create', to: 'main#create', as: :data_mains
  #viewing data on index
  get '/view/:id', to: 'main#view', as: :view
  #update the form -> only as admin
  patch '/view/:id/edit', to: 'main#update'
  #delete the post
  delete '/view/:id', to: 'main#destroy', as: :destroy_data_main
  #edit post -> only as admin 
  get '/view/:id/edit', to: 'main#edit', as: :data_main

  # Defines the root path route ("/")
  root "main#index", as: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/data_main.rb
class DataMain < ApplicationRecord

    validates :title, presence: true
    validates :location, presence: true
    validates :era, presence: true
    validates :long, presence: true
    validates :lat, presence: true
    validates :source, presence: true
    validates :opt, presence: true
    # validates :creator_name, presence: true
    # validates :creator_email, presence: true

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "era", "id", "lat", "location", "long", "opt", "source", "status", "title", "updated_at"]
        #["location", "title"]
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController


  def index
    @view_data = DataMain.all 

    #getting all data for map.js
    #params to get are title:, long:, lat:
    @map_data = {}

    #get approved sites and add to view_data to be displayed on map (JSON) 
    @view_data.where(:status => "approved").each do |i|
      @map_data[i.id] = [i.title, i.long, i.lat, i.opt]
    end

  
  end

  def view
    @data_id = DataMain.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to index_path
  end

  def new
    @data_main = DataMain.new

    #text to insert into the form
    @text_guide = %q[
    <p>Title</p><br><hr> 
    <p>Details</p><br><hr> 
    <a href = '#' target= '_blank'> Link </a>]

  end
  
  def create
    @data_main = DataMain.new(post_params)
    
    if @data_main.save
      redirect_to index_path
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def edit
    if user_signed_in?
      @data_id = DataMain.find(params[:id])
    else
      redirect_to view_path
    end
  end

  def update
    @data_id = DataMain.find(params[:id])
    if @data_id.update(post_params)
      redirect_to view_path
    else
      render :data_main
    end
  end

  def destroy
    @data_id = DataMain.find(params[:id])
    @data_id.destroy
    redirect_to index_path
  end

  
  private 

  def post_params
    params.require(:data_main).permit(:title, :location, :era, :long, :lat, :source, :status, :opt, :creator_email, :creator_name, :edit_date, :editor_email)
  end

end



#notes

#before_action :authenticate_user!, except: [:index, ]

#check if logged in
#if user_signed_in?

#if not 
#<% if !user_signed_in? %>

#logout
#destroy_user_session_path, method: :delete, this is for form submission

#login
#new_user_session_path

# <%= link_to ''.html_safe, index_path %>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digital Archaeological Atlas of the Classical East</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />        
    <%= stylesheet_link_tag 'application', 'application.css' %>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

  </head>

  <body>



    <%= yield %>

    
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer>
    <div id = "footer_main">
        <h style = "float: left; color:white; font-size: 3vmin; margin-left: 10px; margin-top: 20px; text-align: center; ">Digital Archaeological Atlas of the Classical East (DAACE)</h>
        <div style = "color: #F4CECE;" id = "footer_bottom">
            <p style = "float: left; font-size: 1.5vh; margin-left: 10px; text-align: center;">Created by Ali Kesserwani (University of Alabama at Birmingham)</p>
        </div>

    </div>
</footer>

app/views/layouts/shared/_navbar.html.erb
<nav>
    <div id="nav">
        <% if request.path != "/" %>
            <%= link_to ' <div style = "margin:0; float:left;" class = "icon"><span class="material-symbols-outlined  ">arrow_back_ios</span></div>'.html_safe, index_path %>
        <%end%>
        <div style = "float: left; width: 60%; height: 100%; margin-left: 10px; margin-top: 1.5rem;">
            <h id = "title" style = "float:left; display: inline-block; word-wrap: break-word;">Digital Archaeological Atlas of the Classical East</h>
        </div>
        <% if user_signed_in?%>
            <%= link_to '<div id = "login_button" class = "icon"><span class="material-symbols-outlined  ">logout</span></div>'.html_safe, destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to sign out?'}  %>
        <%else%>
            <%= link_to '<div id = "login_button" class = "icon"><span class="material-symbols-outlined  ">login</span></div>'.html_safe, new_user_session_path %>
        <%end%>
    </div>
</nav>

app/views/main/edit.html.erb
<%= render partial: "layouts/shared/navbar"%>


    
<%= form_with model: @data_id do |form|%>

    <% if form.object.errors.any?%>
    <div>
    <%form.object.errors.full_messages.each do |message| %>
       <br> <center><div> <%= message %> </div></center>
        <%end%>
    </div>
    <%end%>


    <div class="wrapper">
            <div class = "list_1">
                <div class="side_list" style = "margin:50px; width:80%;">
                    <h style = "color:#484848; font-size: 4vmin; text-align: center; margin-left:20px;">Site Submission</h><br><br>
                        <%= form.text_field :creator_name, placeholder: 'Name', id: 'name', type: 'text', class: 'custom_form', style: 'height:10%;'  %>
                        <%= form.text_field :creator_email, placeholder: 'Email', id: 'email_form', type: 'text', class: 'custom_form', style: 'height:10%;' %>
                        <hr>
                        <%= form.text_field :title, placeholder: 'Site Name', id: 'site_name', type: 'text', class: 'custom_form', style: 'height:10%;'  %>
                        <%= form.text_field :location, placeholder: 'Location', id: 'site_location', type: 'text', class: 'custom_form', style: 'height:10%;' %>
                        <%= form.text_field :era, placeholder: 'Period', id: 'site_period', type: 'text', class: 'custom_form', style: 'height:10%;' %>
                        <%= form.text_field :long, placeholder: 'Longitude', id: 'site_long', type: 'text', class: 'custom_form', style: 'height:10%;' %>
                        <%= form.text_field :lat, placeholder: 'Latitude', id: 'site_lat', type: 'text', class: 'custom_form', style: 'height:10%;' %>

                        <%= form.hidden_field :edit_date, value: Time.now.strftime("%d/%m/%Y %H:%M") %>
                        <%= form.hidden_field :editor_email, value: current_user.email %>

                </div>
            </div>

                <div class = "list_2">
                    <div class="side_list" style = "display: flex; justify-content: center;flex-direction: column;"><br><br>
                        <h style = "color:#484848; font-size: 4vmin; text-align: center;">Site Information</h><br>
                        <%= form.text_area :source, id: 'site_info', type: 'text', class: 'custom_form', style: 'position:relative;height:100%;width:95%;padding:20px;'%>

                    </div>
                </div>

            
        </div>
    

        <div class = "list_3">
            <div class="side_list" style = "width:100%;height:100%;background-color:#EAEAEA;">
                <div class = "wrapper" style = "position:relative;margin:50px;padding:20px; top:20px;">
                    <div style = "width: 30%; height:100px;margin:auto;">
                        <%= form.radio_button :status, 'approved'%> 
                        <%= form.label :status, 'Approved', :value => 'approved'%><br>
                        <%= form.radio_button :status, 'unapproved' %>
                        <%= form.label :status, 'Unapproved', :value => 'unapproved'%>
                    </div>
                    <div style = "width: 30%; height:100px;margin:auto;">
                            <%= form.radio_button :opt, 'green'%> 
                            <%= form.label :opt, 'Active and Maintained', :value => 'green'%><br>
                            <%= form.radio_button :opt, 'red'%> 
                            <%= form.label :opt, 'Endangered/Abandoned', :value => 'red'%><br>
                            <%= form.radio_button :opt, 'blue' %>
                            <%= form.label :opt, 'Potential Site', :value => 'blue'%>
                    </div>

                    <div style = "width: 40%; height:100px; margin:auto; display:inline-block; margin-left:200px;">
                        <div style = "display:inline-block;">
                            <%= form.button 'Update', class: 'button', style: 'font-size: 3vmin; border:none; width: 120px; height:60px;'%>
                        </div>
                        <%end%>
                        <div style = "display:inline-block;">
                            <%= button_to "Delete", destroy_data_main_path(@data_id), method: :delete, class: "button", style: "font-size: 3vmin; border:none; width: 120px; height:60px; background-color:#8b7e7e;", onclick: "return confirmDestroy('Are you sure want to delete this?')" %>
                        </div>

                        <script>
                            function confirmDestroy(message) {
                                if (!confirm(message)) {
                                    return false;
                                }
                                }
                        </script>
                    </div>
                </div>
            </div>
        </div>



<%= render partial: "layouts/shared/footer"%>

app/views/main/index.html.erb
<%= render partial: "layouts/shared/navbar"%>

<main>

    <div class="wrapper">

        <div class = "list_1">
            <div class="side_list">

                <!--Main Data-->
                <% @view_data.where(:status => "approved").each do |p| %>
                    <%= link_to view_path(p) do %>
                        <div class = "list_element">
                            <div class = "text_list_container"> 
                                <h class = "list_header"><%=p.title %></h>
                                <p class = "list_para"> <%=p.location %></p>
                                <p class = "list_para"> Period: <%=p.era %></p>
                            </div>
                        </div><br>
                    <%end%>
                <%end%>
                <div style="height: 100px"></div>
            </div>
        </div>




        <!--Leaflet Map Container - only shows in user view - not admin view -->
        <div class = "list_2">
            <div class="side_list" id = "map_container">

            <!--Show submission boxes on top only if logged in-->
            <%if user_signed_in?%>
                    <div id = "status_box">
                        <h style = "color: #666; font-size: 30px; margin-left: 20px;">Submissions</h>
                    </div>

                <!--Displays submission box for Admin view-->
                <% @view_data.where(:status => "unapproved").each do |p| %>
                    <%= link_to view_path(p) do %>
                        <div class = "list_element">
                            <div class = "text_list_container"> 
                                <h class = "list_header"><%=p.title %></h>
                                <p class = "list_para"> <%=p.location %></p>
                            </div>
                        </div><br>
                    <%end%>

                <%end%>

                <div style="height: 100px"></div>
            <%else%>
                <!--Display map when not logged in-->
                <div id="map" style = "width: 100%; height: 100%; z-index:1;"></div>
            <%end%>
            </div>
        </div>

    <div style = "height:10vh;"></div>
        <!--Container for buttons-->
    <div style = "position: fixed; left: 0; bottom: 0; height:200px; width: 100%;display:sticky; z-index:999;">
        <!--Add Button on left -->
        <%= link_to '<div style = "float:left; margin:50px;" class = "circle_button"><span class="material-symbols-outlined" style = "color:white; font-size: 40px;">add</span></div>'.html_safe, new_path %>
    </div>

    </div>



    <!--Leaflet Map -->
    <script>
        //Pass @map_data from controller to map.js file 
        var map_data =  <%= raw @map_data.to_json %>;


        //create marker with color as argument - map_data[key][3]
        function colored_icon(color){
            return green = L.icon({
                iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-' + color + '.png',
                shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
                iconSize: [25, 41],
                iconAnchor: [12, 41],
                popupAnchor: [1, -34],
                shadowSize: [41, 41]
            });
        }

        var map = L.map ('map')
        map.setView([34.0047, 36.2110], 5);

        L.tileLayer('https://api.maptiler.com/maps/streets-v2/{z}/{x}/{y}.png?key=gYAdQevZTRyC4s7dinqH',{
            attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
        }).addTo(map)


        //Load all pins
        for (let key in map_data) {
            var marker = L.marker([map_data[key][1], map_data[key][2]],  {icon: colored_icon(map_data[key][3])});
            //add onclick functions for tag with: name, location, era, info button as link 
            marker.on("click", function (event) {
                window.location.href = '/view/' + key;
            });

            marker.addTo(map);
        }

         //Legend
        var legend = L.control({ position: "bottomleft" });

        legend.onAdd = function(map) {
        var div = L.DomUtil.create("div", "legend");
        div.innerHTML += "<h4>Key</h4>";
        div.innerHTML += '<img src = "https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png" style = "width:15px;"><span>&nbsp;&nbsp;Active/Regulated</span><br>';
        div.innerHTML += '<img src = "https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png" style = "width:15px;"><span>&nbsp;&nbsp;Abandoned/At Risk</span><br>';
        div.innerHTML += '<img src = "https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-blue.png" style = "width:15px;"><span>&nbsp;&nbsp;Potential Site</span><br>';
        
        return div;
        };

        legend.addTo(map);

        //Search Button Returns coming soon
        var btn = document.getElementById("search_button");
        btn.onclick = function(){
            alert("Search function coming soon");
        }


    </script>
    <!--Style for legend section-->
    <style>
        /*Legend specific*/
        .legend {
        padding: 6px 8px;
        font: 14px Arial, Helvetica, sans-serif;
        background: white;
        background: rgba(255, 255, 255, 0.8);
        /*box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);*/
        /*border-radius: 5px;*/
        line-height: 24px;
        color: #555;
        }
        .legend h4 {
        text-align: center;
        font-size: 16px;
        margin: 2px 12px 8px;
        color: #777;
        }

        .legend span {
        position: relative;
        bottom: 3px;
        }

    </style>




 </main>



    <%= render partial: "layouts/shared/footer"%>


</html>

app/views/main/new.html.erb
<%= render partial: "layouts/shared/navbar"%>
    
    
<%= form_with model: @data_main do |form|%>

    <% if form.object.errors.any?%>
    <div>
    <%form.object.errors.full_messages.each do |message| %>
       <br> <center><div> <%= message %> </div></center>
        <%end%>
    </div>
    <%end%>

<div class="wrapper">
            <div class = "list_1" style = "overflow-y:scroll;overflow: -moz-scrollbars-vertical; ">
                <div class="side_list" style = "margin:50px; width:80%;">
                    <h style = "color:#484848; font-size: 4vmin; text-align: center; margin-left:20px;">Site Submission</h><br><br>

                        <%= form.text_field :creator_name, placeholder: 'Name', id: 'name', type: 'text', class: 'custom_form', style: 'height:10%;', value: (current_user.name if user_signed_in?) %>
                        <%= form.text_field :creator_email, placeholder: 'Email', id: 'email_form', type: 'text', class: 'custom_form', style: 'height:10%;',value: (current_user.email if user_signed_in?) %>
                        <hr>
                        <%= form.text_field :title, placeholder: 'Site Name', id: 'site_name', type: 'text', class: 'custom_form', style: 'height:10%;'  %>
                        <%= form.text_field :location, placeholder: 'Location', id: 'site_location', type: 'text', class: 'custom_form', style: 'height:10%;' %>
                        <%= form.text_field :era, placeholder: 'Period', id: 'site_period', type: 'text', class: 'custom_form', style: 'height:10%;' %>
                        <%= form.text_field :long, placeholder: 'Longitude', id: 'site_long', type: 'text', class: 'custom_form', style: 'height:10%;' %>
                        <%= form.text_field :lat, placeholder: 'Latitude', id: 'site_lat', type: 'text', class: 'custom_form', style: 'height:10%;' %>

                        <%= form.hidden_field :create_date, value: Time.now.strftime("%d/%m/%Y %H:%M") %>
                </div>
            </div>

            <div class = "list_2" style = "overflow-y:scroll;overflow: -moz-scrollbars-vertical;">
                <div class="side_list"><br><br>
                    <h style = "color:#484848; font-size: 4vmin; text-align: center; margin:20px;">Site Information</h><br>
                        <%= form.text_area :source, id: 'site_info', type: 'text', class: 'custom_form', style: 'height:100%;width: 95%;padding:20px;', value: @text_guide%>
                            <br><br><br>

                            <!--Only allow approval through site submission if signed in -->
                            <% if user_signed_in?%>
                            <div style = "width: 70%; height:10%; margin:auto;">
                                <%= form.radio_button :status, 'approved'%> 
                                <%= form.label :status, 'Approved', :value => 'approved'%><br>
                                <%= form.radio_button :status, 'unapproved' %>
                                <%= form.label :status, 'Unapproved', :value => 'unapproved'%>
                            </div>
                            <%end%>

                            <div style = "width: 70%; height:10%; margin:auto;">
                                <%= form.radio_button :opt, 'green'%> 
                                <%= form.label :opt, 'Active and Maintained', :value => 'green'%><br>
                                <%= form.radio_button :opt, 'red'%> 
                                <%= form.label :opt, 'Endangered/Abandoned', :value => 'red'%><br>
                                <%= form.radio_button :opt, 'blue' %>
                                <%= form.label :opt, 'Potential Site', :value => 'blue'%>
                            </div>
                            <br><br>
                        <%= form.button 'Submit', class: 'button', style: 'margin:0 auto; font-size: 3vmin; height: 15%; border:none;'%>

                        <!--Allow Admin to be able to approve site without having to go back through edit menu-->
                        <% if !user_signed_in?%>
                            <%= form.hidden_field :status, value: "unapproved" %>
                        <%end%>

                        <br> 
                </div>
            </div>
        
    <%end%>



    <%= render partial: "layouts/shared/footer"%>
</div>

app/views/main/view.html.erb
<%= render partial: "layouts/shared/navbar"%>



<main>
        <div class="wrapper">
                <!--Box 1-->
                <div class = "list_1">
                <div class="container side_list">
                    <div style = "text-align: left; margin-top: 50px; line-height: 1.5; margin-left: 20px; height:50vh;">
                        <h style = "color: #545454; font-size: 4vh;"> <%= @data_id.title%></h><br>
                        <h style = "color: #B56768; font-size: 3.5vh;"><%= @data_id.location%></h>
                        <p style = "color: #B56768; font-size: 3vh;"">Period: <%= @data_id.era%></p>
                        <p style = "color: #B56768; font-size: 3vh;">Coordinates: <%= @data_id.long%>, <%= @data_id.lat%></p>
                        
                        <% if @data_id.opt == "red"%>
                            <p style = "color: #B56768; font-size: 2.5vh;"><b>Site Abandoned or Endangered</b></p>
                        <% elsif @data_id.opt == "blue"%>
                            <p style = "color: #B56768; font-size: 2.5vh;"><b>Potential Site</b></p>
                        <% elsif @data_id.opt == "green"%>
                            <p style = "color: #B56768; font-size: 2.5vh;"><b>Site is active and maintained</b></p>
                        <%end%>
                     </div>

                        <div style = "position:relative; bottom:0;">
                                <div class = "circle_button" id = "map_button" style = "position:relative;top:50px;"><span class="material-symbols-outlined" style = "color:white; font-size: 40px; margin:10px;">map</span></div>
                                <!--Allow edit if signed in-->
                                <%if user_signed_in?%>
                                <%= link_to '<div class = "circle_button" id = "edit_button" style = "position:relative;top:50px;"><span class="material-symbols-outlined" style = "color:white; font-size: 40px;margin:10px;">edit</span></div>'.html_safe, data_main_path %>
                                <%end%>
                        </div>
                </div>
                </div>

                <!--Box 2-->
                <div class = "list_2" style = "overflow-y:scroll;overflow: -moz-scrollbars-vertical; ">
                <div class="container side_list">
                  <div style = "text-align: left; margin-top: 50px; line-height: 1.5; margin-left: 20px;">
                  <div style = "height:60vh; width: 90%;">
                        <p style = "color: #B56768; font-size: 3vh;"> <%= @data_id.source.html_safe %> </p>
                     <div style = "position:relative; bottom:0;">
                        <hr>
                        <p style = "color: #B56768; font-size: 2vh;"> Created by  <%= @data_id.creator_name%> - <%= @data_id.creator_email%>:  <%= @data_id.create_date %> </p>
                        <% if @data_id.editor_email != nil and @data_id.edit_date != nil %>
                                <p style = "color: #B56768; font-size: 2vh;"> Last Edited by <%= @data_id.editor_email%>: <%= @data_id.edit_date%>  </p>
                        <%end%>
                     </div>
                  </div><br>

                </div>

                </div>
        </div>

</main>

<div id="modal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <div id = "map_individual" style = "width:80%; height:80%;">
        <center><h1 style = "color:#B56768;">Satellite Imagery Feature Coming Soon</h1></center>
    </div>
        <script>
                // //stuff for the map display
                // var map_data =  <%= raw @data_id.to_json %>;

                // var map = L.map ('map_individual');
                // map.setView([Math.round(map_data.long * 100) / 100, Math.round(map_data.lat * 100) / 100], 10);

                // L.tileLayer('https://api.maptiler.com/maps/streets-v2/{z}/{x}/{y}.png?key=gYAdQevZTRyC4s7dinqH',{
                // attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
                // }).addTo(map)


                // var marker = L.marker([map_data.long, map_data.lat]);

                // marker.addTo(map);
        </script>

  </div>

</div>

<script>
        //stuff for the modal
        var modal = document.getElementById("modal");

        var btn = document.getElementById("map_button");

        var span = document.getElementsByClassName("close")[0];

        btn.onclick = function() {
        modal.style.display = "block";
        }

        span.onclick = function() {
        modal.style.display = "none";
        }

        window.onclick = function(event) {
        if (event.target == modal) {
        modal.style.display = "none";
        }
        }

</script>



<%= render partial: "layouts/shared/footer"%>